/* eslint-disable no-unused-vars */
import Api from '../Api'
import * as errors from '../Errors'
import {
  getType, isArray, isInt, isObject, isString,
} from '../utils'
/* eslint-enable no-unused-vars */

/**
 * Class ExavaultApiRequestLog
 */
class ExavaultApiRequestLog {
  attributes = {}

  options = {}

  constructor(attributes = {}, options = {}) {
    Object.entries(attributes).forEach(([key, value]) => {
      const normalizedKey = key.replace('?', '')

      this.attributes[normalizedKey] = value

      Object.defineProperty(this, normalizedKey, { value, writable: false })
    })

    this.options = { ...options }
  }

  isLoaded = () => !!this.attributes.id

  // date-time # Start Time of Action. Deprecrated: Use created_at.
  getTimestamp = () => this.attributes.timestamp

  // string # Name of API Endpoint
  getEndpoint = () => this.attributes.endpoint

  // int64 # Exavault API Version
  getVersion = () => this.attributes.version

  // string # IP of requesting client
  getRequestIp = () => this.attributes.request_ip

  // string # HTTP Method
  getRequestMethod = () => this.attributes.request_method

  // string # Error type, if applicable
  getErrorType = () => this.attributes.error_type

  // string # Error message, if applicable
  getErrorMessage = () => this.attributes.error_message

  // string # User-Agent
  getUserAgent = () => this.attributes.user_agent

  // int64 # HTTP Response Code
  getResponseCode = () => this.attributes.response_code

  // boolean # `false` if HTTP Response Code is 4xx or 5xx
  getSuccess = () => this.attributes.success

  // int64 # Duration (in milliseconds)
  getDurationMs = () => this.attributes.duration_ms

  // date-time # Start Time of Action
  getCreatedAt = () => this.attributes.created_at

  // Parameters:
  //   cursor - string - Used for pagination.  When a list request has more records available, cursors are provided in the response headers `X-Files-Cursor-Next` and `X-Files-Cursor-Prev`.  Send one of those cursor value here to resume an existing list from the next available record.  Note: many of our SDKs have iterator methods that will automatically handle cursor-based pagination.
  //   per_page - int64 - Number of records to show per page.  (Max: 10,000, 1,000 or less is recommended).
  //   filter - object - If set, return records where the specified field is equal to the supplied value. Valid fields are `start_date`, `end_date`, `request_ip`, `request_method`, `success` or `created_at`. Valid field combinations are `[ start_date ]`, `[ end_date ]`, `[ request_ip ]`, `[ request_method ]`, `[ success ]`, `[ created_at ]`, `[ start_date, end_date ]`, `[ start_date, request_ip ]`, `[ start_date, request_method ]`, `[ start_date, success ]`, `[ start_date, created_at ]`, `[ end_date, request_ip ]`, `[ end_date, request_method ]`, `[ end_date, success ]`, `[ end_date, created_at ]`, `[ request_ip, request_method ]`, `[ request_ip, success ]`, `[ request_ip, created_at ]`, `[ request_method, success ]`, `[ request_method, created_at ]`, `[ success, created_at ]`, `[ start_date, end_date, request_ip ]`, `[ start_date, end_date, request_method ]`, `[ start_date, end_date, success ]`, `[ start_date, end_date, created_at ]`, `[ start_date, request_ip, request_method ]`, `[ start_date, request_ip, success ]`, `[ start_date, request_ip, created_at ]`, `[ start_date, request_method, success ]`, `[ start_date, request_method, created_at ]`, `[ start_date, success, created_at ]`, `[ end_date, request_ip, request_method ]`, `[ end_date, request_ip, success ]`, `[ end_date, request_ip, created_at ]`, `[ end_date, request_method, success ]`, `[ end_date, request_method, created_at ]`, `[ end_date, success, created_at ]`, `[ request_ip, request_method, success ]`, `[ request_ip, request_method, created_at ]`, `[ request_ip, success, created_at ]`, `[ request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method ]`, `[ start_date, end_date, request_ip, success ]`, `[ start_date, end_date, request_ip, created_at ]`, `[ start_date, end_date, request_method, success ]`, `[ start_date, end_date, request_method, created_at ]`, `[ start_date, end_date, success, created_at ]`, `[ start_date, request_ip, request_method, success ]`, `[ start_date, request_ip, request_method, created_at ]`, `[ start_date, request_ip, success, created_at ]`, `[ start_date, request_method, success, created_at ]`, `[ end_date, request_ip, request_method, success ]`, `[ end_date, request_ip, request_method, created_at ]`, `[ end_date, request_ip, success, created_at ]`, `[ end_date, request_method, success, created_at ]`, `[ request_ip, request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method, success ]`, `[ start_date, end_date, request_ip, request_method, created_at ]`, `[ start_date, end_date, request_ip, success, created_at ]`, `[ start_date, end_date, request_method, success, created_at ]`, `[ start_date, request_ip, request_method, success, created_at ]` or `[ end_date, request_ip, request_method, success, created_at ]`.
  //   filter_gt - object - If set, return records where the specified field is greater than the supplied value. Valid fields are `created_at`. Valid field combinations are `[ start_date ]`, `[ end_date ]`, `[ request_ip ]`, `[ request_method ]`, `[ success ]`, `[ created_at ]`, `[ start_date, end_date ]`, `[ start_date, request_ip ]`, `[ start_date, request_method ]`, `[ start_date, success ]`, `[ start_date, created_at ]`, `[ end_date, request_ip ]`, `[ end_date, request_method ]`, `[ end_date, success ]`, `[ end_date, created_at ]`, `[ request_ip, request_method ]`, `[ request_ip, success ]`, `[ request_ip, created_at ]`, `[ request_method, success ]`, `[ request_method, created_at ]`, `[ success, created_at ]`, `[ start_date, end_date, request_ip ]`, `[ start_date, end_date, request_method ]`, `[ start_date, end_date, success ]`, `[ start_date, end_date, created_at ]`, `[ start_date, request_ip, request_method ]`, `[ start_date, request_ip, success ]`, `[ start_date, request_ip, created_at ]`, `[ start_date, request_method, success ]`, `[ start_date, request_method, created_at ]`, `[ start_date, success, created_at ]`, `[ end_date, request_ip, request_method ]`, `[ end_date, request_ip, success ]`, `[ end_date, request_ip, created_at ]`, `[ end_date, request_method, success ]`, `[ end_date, request_method, created_at ]`, `[ end_date, success, created_at ]`, `[ request_ip, request_method, success ]`, `[ request_ip, request_method, created_at ]`, `[ request_ip, success, created_at ]`, `[ request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method ]`, `[ start_date, end_date, request_ip, success ]`, `[ start_date, end_date, request_ip, created_at ]`, `[ start_date, end_date, request_method, success ]`, `[ start_date, end_date, request_method, created_at ]`, `[ start_date, end_date, success, created_at ]`, `[ start_date, request_ip, request_method, success ]`, `[ start_date, request_ip, request_method, created_at ]`, `[ start_date, request_ip, success, created_at ]`, `[ start_date, request_method, success, created_at ]`, `[ end_date, request_ip, request_method, success ]`, `[ end_date, request_ip, request_method, created_at ]`, `[ end_date, request_ip, success, created_at ]`, `[ end_date, request_method, success, created_at ]`, `[ request_ip, request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method, success ]`, `[ start_date, end_date, request_ip, request_method, created_at ]`, `[ start_date, end_date, request_ip, success, created_at ]`, `[ start_date, end_date, request_method, success, created_at ]`, `[ start_date, request_ip, request_method, success, created_at ]` or `[ end_date, request_ip, request_method, success, created_at ]`.
  //   filter_gteq - object - If set, return records where the specified field is greater than or equal the supplied value. Valid fields are `created_at`. Valid field combinations are `[ start_date ]`, `[ end_date ]`, `[ request_ip ]`, `[ request_method ]`, `[ success ]`, `[ created_at ]`, `[ start_date, end_date ]`, `[ start_date, request_ip ]`, `[ start_date, request_method ]`, `[ start_date, success ]`, `[ start_date, created_at ]`, `[ end_date, request_ip ]`, `[ end_date, request_method ]`, `[ end_date, success ]`, `[ end_date, created_at ]`, `[ request_ip, request_method ]`, `[ request_ip, success ]`, `[ request_ip, created_at ]`, `[ request_method, success ]`, `[ request_method, created_at ]`, `[ success, created_at ]`, `[ start_date, end_date, request_ip ]`, `[ start_date, end_date, request_method ]`, `[ start_date, end_date, success ]`, `[ start_date, end_date, created_at ]`, `[ start_date, request_ip, request_method ]`, `[ start_date, request_ip, success ]`, `[ start_date, request_ip, created_at ]`, `[ start_date, request_method, success ]`, `[ start_date, request_method, created_at ]`, `[ start_date, success, created_at ]`, `[ end_date, request_ip, request_method ]`, `[ end_date, request_ip, success ]`, `[ end_date, request_ip, created_at ]`, `[ end_date, request_method, success ]`, `[ end_date, request_method, created_at ]`, `[ end_date, success, created_at ]`, `[ request_ip, request_method, success ]`, `[ request_ip, request_method, created_at ]`, `[ request_ip, success, created_at ]`, `[ request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method ]`, `[ start_date, end_date, request_ip, success ]`, `[ start_date, end_date, request_ip, created_at ]`, `[ start_date, end_date, request_method, success ]`, `[ start_date, end_date, request_method, created_at ]`, `[ start_date, end_date, success, created_at ]`, `[ start_date, request_ip, request_method, success ]`, `[ start_date, request_ip, request_method, created_at ]`, `[ start_date, request_ip, success, created_at ]`, `[ start_date, request_method, success, created_at ]`, `[ end_date, request_ip, request_method, success ]`, `[ end_date, request_ip, request_method, created_at ]`, `[ end_date, request_ip, success, created_at ]`, `[ end_date, request_method, success, created_at ]`, `[ request_ip, request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method, success ]`, `[ start_date, end_date, request_ip, request_method, created_at ]`, `[ start_date, end_date, request_ip, success, created_at ]`, `[ start_date, end_date, request_method, success, created_at ]`, `[ start_date, request_ip, request_method, success, created_at ]` or `[ end_date, request_ip, request_method, success, created_at ]`.
  //   filter_prefix - object - If set, return records where the specified field is prefixed by the supplied value. Valid fields are `request_ip` and `request_method`. Valid field combinations are `[ start_date ]`, `[ end_date ]`, `[ request_ip ]`, `[ request_method ]`, `[ success ]`, `[ created_at ]`, `[ start_date, end_date ]`, `[ start_date, request_ip ]`, `[ start_date, request_method ]`, `[ start_date, success ]`, `[ start_date, created_at ]`, `[ end_date, request_ip ]`, `[ end_date, request_method ]`, `[ end_date, success ]`, `[ end_date, created_at ]`, `[ request_ip, request_method ]`, `[ request_ip, success ]`, `[ request_ip, created_at ]`, `[ request_method, success ]`, `[ request_method, created_at ]`, `[ success, created_at ]`, `[ start_date, end_date, request_ip ]`, `[ start_date, end_date, request_method ]`, `[ start_date, end_date, success ]`, `[ start_date, end_date, created_at ]`, `[ start_date, request_ip, request_method ]`, `[ start_date, request_ip, success ]`, `[ start_date, request_ip, created_at ]`, `[ start_date, request_method, success ]`, `[ start_date, request_method, created_at ]`, `[ start_date, success, created_at ]`, `[ end_date, request_ip, request_method ]`, `[ end_date, request_ip, success ]`, `[ end_date, request_ip, created_at ]`, `[ end_date, request_method, success ]`, `[ end_date, request_method, created_at ]`, `[ end_date, success, created_at ]`, `[ request_ip, request_method, success ]`, `[ request_ip, request_method, created_at ]`, `[ request_ip, success, created_at ]`, `[ request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method ]`, `[ start_date, end_date, request_ip, success ]`, `[ start_date, end_date, request_ip, created_at ]`, `[ start_date, end_date, request_method, success ]`, `[ start_date, end_date, request_method, created_at ]`, `[ start_date, end_date, success, created_at ]`, `[ start_date, request_ip, request_method, success ]`, `[ start_date, request_ip, request_method, created_at ]`, `[ start_date, request_ip, success, created_at ]`, `[ start_date, request_method, success, created_at ]`, `[ end_date, request_ip, request_method, success ]`, `[ end_date, request_ip, request_method, created_at ]`, `[ end_date, request_ip, success, created_at ]`, `[ end_date, request_method, success, created_at ]`, `[ request_ip, request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method, success ]`, `[ start_date, end_date, request_ip, request_method, created_at ]`, `[ start_date, end_date, request_ip, success, created_at ]`, `[ start_date, end_date, request_method, success, created_at ]`, `[ start_date, request_ip, request_method, success, created_at ]` or `[ end_date, request_ip, request_method, success, created_at ]`.
  //   filter_lt - object - If set, return records where the specified field is less than the supplied value. Valid fields are `created_at`. Valid field combinations are `[ start_date ]`, `[ end_date ]`, `[ request_ip ]`, `[ request_method ]`, `[ success ]`, `[ created_at ]`, `[ start_date, end_date ]`, `[ start_date, request_ip ]`, `[ start_date, request_method ]`, `[ start_date, success ]`, `[ start_date, created_at ]`, `[ end_date, request_ip ]`, `[ end_date, request_method ]`, `[ end_date, success ]`, `[ end_date, created_at ]`, `[ request_ip, request_method ]`, `[ request_ip, success ]`, `[ request_ip, created_at ]`, `[ request_method, success ]`, `[ request_method, created_at ]`, `[ success, created_at ]`, `[ start_date, end_date, request_ip ]`, `[ start_date, end_date, request_method ]`, `[ start_date, end_date, success ]`, `[ start_date, end_date, created_at ]`, `[ start_date, request_ip, request_method ]`, `[ start_date, request_ip, success ]`, `[ start_date, request_ip, created_at ]`, `[ start_date, request_method, success ]`, `[ start_date, request_method, created_at ]`, `[ start_date, success, created_at ]`, `[ end_date, request_ip, request_method ]`, `[ end_date, request_ip, success ]`, `[ end_date, request_ip, created_at ]`, `[ end_date, request_method, success ]`, `[ end_date, request_method, created_at ]`, `[ end_date, success, created_at ]`, `[ request_ip, request_method, success ]`, `[ request_ip, request_method, created_at ]`, `[ request_ip, success, created_at ]`, `[ request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method ]`, `[ start_date, end_date, request_ip, success ]`, `[ start_date, end_date, request_ip, created_at ]`, `[ start_date, end_date, request_method, success ]`, `[ start_date, end_date, request_method, created_at ]`, `[ start_date, end_date, success, created_at ]`, `[ start_date, request_ip, request_method, success ]`, `[ start_date, request_ip, request_method, created_at ]`, `[ start_date, request_ip, success, created_at ]`, `[ start_date, request_method, success, created_at ]`, `[ end_date, request_ip, request_method, success ]`, `[ end_date, request_ip, request_method, created_at ]`, `[ end_date, request_ip, success, created_at ]`, `[ end_date, request_method, success, created_at ]`, `[ request_ip, request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method, success ]`, `[ start_date, end_date, request_ip, request_method, created_at ]`, `[ start_date, end_date, request_ip, success, created_at ]`, `[ start_date, end_date, request_method, success, created_at ]`, `[ start_date, request_ip, request_method, success, created_at ]` or `[ end_date, request_ip, request_method, success, created_at ]`.
  //   filter_lteq - object - If set, return records where the specified field is less than or equal the supplied value. Valid fields are `created_at`. Valid field combinations are `[ start_date ]`, `[ end_date ]`, `[ request_ip ]`, `[ request_method ]`, `[ success ]`, `[ created_at ]`, `[ start_date, end_date ]`, `[ start_date, request_ip ]`, `[ start_date, request_method ]`, `[ start_date, success ]`, `[ start_date, created_at ]`, `[ end_date, request_ip ]`, `[ end_date, request_method ]`, `[ end_date, success ]`, `[ end_date, created_at ]`, `[ request_ip, request_method ]`, `[ request_ip, success ]`, `[ request_ip, created_at ]`, `[ request_method, success ]`, `[ request_method, created_at ]`, `[ success, created_at ]`, `[ start_date, end_date, request_ip ]`, `[ start_date, end_date, request_method ]`, `[ start_date, end_date, success ]`, `[ start_date, end_date, created_at ]`, `[ start_date, request_ip, request_method ]`, `[ start_date, request_ip, success ]`, `[ start_date, request_ip, created_at ]`, `[ start_date, request_method, success ]`, `[ start_date, request_method, created_at ]`, `[ start_date, success, created_at ]`, `[ end_date, request_ip, request_method ]`, `[ end_date, request_ip, success ]`, `[ end_date, request_ip, created_at ]`, `[ end_date, request_method, success ]`, `[ end_date, request_method, created_at ]`, `[ end_date, success, created_at ]`, `[ request_ip, request_method, success ]`, `[ request_ip, request_method, created_at ]`, `[ request_ip, success, created_at ]`, `[ request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method ]`, `[ start_date, end_date, request_ip, success ]`, `[ start_date, end_date, request_ip, created_at ]`, `[ start_date, end_date, request_method, success ]`, `[ start_date, end_date, request_method, created_at ]`, `[ start_date, end_date, success, created_at ]`, `[ start_date, request_ip, request_method, success ]`, `[ start_date, request_ip, request_method, created_at ]`, `[ start_date, request_ip, success, created_at ]`, `[ start_date, request_method, success, created_at ]`, `[ end_date, request_ip, request_method, success ]`, `[ end_date, request_ip, request_method, created_at ]`, `[ end_date, request_ip, success, created_at ]`, `[ end_date, request_method, success, created_at ]`, `[ request_ip, request_method, success, created_at ]`, `[ start_date, end_date, request_ip, request_method, success ]`, `[ start_date, end_date, request_ip, request_method, created_at ]`, `[ start_date, end_date, request_ip, success, created_at ]`, `[ start_date, end_date, request_method, success, created_at ]`, `[ start_date, request_ip, request_method, success, created_at ]` or `[ end_date, request_ip, request_method, success, created_at ]`.
  static list = async (params = {}, options = {}) => {
    if (params.cursor && !isString(params.cursor)) {
      throw new errors.InvalidParameterError(`Bad parameter: cursor must be of type String, received ${getType(params.cursor)}`)
    }

    if (params.per_page && !isInt(params.per_page)) {
      throw new errors.InvalidParameterError(`Bad parameter: per_page must be of type Int, received ${getType(params.per_page)}`)
    }

    const response = await Api.sendRequest('/exavault_api_request_logs', 'GET', params, options)

    return response?.data?.map(obj => new ExavaultApiRequestLog(obj, options)) || []
  }

  static all = (params = {}, options = {}) =>
    ExavaultApiRequestLog.list(params, options)
}

export default ExavaultApiRequestLog

module.exports = ExavaultApiRequestLog
module.exports.default = ExavaultApiRequestLog
